services:
  db:
    image: postgres
    container_name: db_students
    restart: always
    ports:
      - 5430:5432
    env_file:
      - .env
    volumes:
      - pg:/var/lib/postgresql/data
    
  node_app_students:
    container_name: node_app_students
    build: .
    ports:
      - 5000:5000
    depends_on:
      - db
    env_file:
      - .env
      
volumes:
  pg: